//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKADGroupTestTask.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public string Uri { get; set; }
        public double ResponceTimeMin { get; set; }
        public double ResponceTimeMax { get; set; }
        public string Site_Uri { get; set; }

        public virtual Site Site { get; set; }
    }
}
